name: Deploy

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-push-deploy:

    concurrency:
      group: delpoy
      cancel-in-progress: true

    runs-on: windows-latest
    environment: aws
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: windows run
        run: |
          docker run mcr.microsoft.com/windows/servercore:ltsc2022
